COMPOSE = docker compose -f docker-compose.yml
LIVEKIT_NODE_IP ?= $(shell hostname -I 2>/dev/null | awk '{print $$1}')
LIVEKIT_PORT ?= 7880
LIVEKIT_TCP_PORT ?= 7881
LIVEKIT_UDP_PORT ?= 7882
BUD_PORT ?= 3002
LIVEKIT_PUBLIC_URL ?= ws://127.0.0.1:$(LIVEKIT_PORT)
QWEN_MODEL_MOUNT ?= qwen-models

.PHONY: up up-d down clean logs ps test

up:
	LIVEKIT_NODE_IP=$(LIVEKIT_NODE_IP) LIVEKIT_PORT=$(LIVEKIT_PORT) LIVEKIT_TCP_PORT=$(LIVEKIT_TCP_PORT) LIVEKIT_UDP_PORT=$(LIVEKIT_UDP_PORT) BUD_PORT=$(BUD_PORT) LIVEKIT_PUBLIC_URL=$(LIVEKIT_PUBLIC_URL) QWEN_MODEL_MOUNT=$(QWEN_MODEL_MOUNT) $(COMPOSE) up --build

up-d:
	LIVEKIT_NODE_IP=$(LIVEKIT_NODE_IP) LIVEKIT_PORT=$(LIVEKIT_PORT) LIVEKIT_TCP_PORT=$(LIVEKIT_TCP_PORT) LIVEKIT_UDP_PORT=$(LIVEKIT_UDP_PORT) BUD_PORT=$(BUD_PORT) LIVEKIT_PUBLIC_URL=$(LIVEKIT_PUBLIC_URL) QWEN_MODEL_MOUNT=$(QWEN_MODEL_MOUNT) $(COMPOSE) up --build -d

down:
	$(COMPOSE) down

clean:
	$(COMPOSE) down -v

logs:
	$(COMPOSE) logs -f

ps:
	$(COMPOSE) ps

test:
	$(COMPOSE) run --rm bud npm test
